// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShkandalInfrastructure;

#nullable disable

namespace ShkandalInfrastructure.Migrations
{
    [DbContext(typeof(ShkandalDbContext))]
    [Migration("20260125101802_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CategoryCluster", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("integer")
                        .HasColumnName("categoriesId");

                    b.Property<int>("ClustersId")
                        .HasColumnType("integer")
                        .HasColumnName("clustersId");

                    b.HasKey("CategoriesId", "ClustersId")
                        .HasName("pK_categoryCluster");

                    b.HasIndex("ClustersId")
                        .HasDatabaseName("iX_categoryCluster_clustersId");

                    b.ToTable("categoryCluster", (string)null);
                });

            modelBuilder.Entity("ShkandalData.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .HasColumnType("text")
                        .HasColumnName("author");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("integer")
                        .HasColumnName("cluster_id");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<string>("FeaturedImageURL")
                        .HasColumnType("text")
                        .HasColumnName("featured_image_url");

                    b.Property<bool>("IsChecked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_checked");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_relevant");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<int>("MediaId")
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pK_article");

                    b.HasIndex("ClusterId")
                        .HasDatabaseName("iX_article_clusterId");

                    b.HasIndex("MediaId")
                        .HasDatabaseName("iX_article_mediaId");

                    b.ToTable("article", (string)null);
                });

            modelBuilder.Entity("ShkandalData.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pK_category");

                    b.ToTable("category", (string)null);
                });

            modelBuilder.Entity("ShkandalData.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FeaturedImageURL")
                        .HasColumnType("text")
                        .HasColumnName("featured_image_url");

                    b.Property<bool>("IsRelevant")
                        .HasColumnType("boolean")
                        .HasColumnName("is_relevant");

                    b.Property<DateTime?>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<int>("ViewCounter")
                        .HasColumnType("integer")
                        .HasColumnName("view_counter");

                    b.HasKey("Id")
                        .HasName("pK_cluster");

                    b.ToTable("cluster", (string)null);
                });

            modelBuilder.Entity("ShkandalData.Models.Media", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("SitemapIndexURL")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sitemap_index_url");

                    b.HasKey("Id")
                        .HasName("pK_media");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("ShkandalData.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<int>("Role")
                        .HasColumnType("integer")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pK_app_user");

                    b.ToTable("app_user", (string)null);
                });

            modelBuilder.Entity("CategoryCluster", b =>
                {
                    b.HasOne("ShkandalData.Models.Category", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_categoryCluster_category_categoriesId");

                    b.HasOne("ShkandalData.Models.Cluster", null)
                        .WithMany()
                        .HasForeignKey("ClustersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fK_categoryCluster_cluster_clustersId");
                });

            modelBuilder.Entity("ShkandalData.Models.Article", b =>
                {
                    b.HasOne("ShkandalData.Models.Cluster", "Cluster")
                        .WithMany("Articles")
                        .HasForeignKey("ClusterId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fK_article_cluster_clusterId");

                    b.HasOne("ShkandalData.Models.Media", "Media")
                        .WithMany("Articles")
                        .HasForeignKey("MediaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fK_article_media_mediaId");

                    b.Navigation("Cluster");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("ShkandalData.Models.Cluster", b =>
                {
                    b.Navigation("Articles");
                });

            modelBuilder.Entity("ShkandalData.Models.Media", b =>
                {
                    b.Navigation("Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
